@startuml

note "观察者模式" as N1

Subject <|-- ConcreteSubject
Subject o-- Observer : Notifies >
Observer <|.. ConcreteObserver

abstract class Subject {
    observers
    ==
    addObserver
    deleteObserve
    notifyObservers
    getSubjectStatus
}

class ConcreteSubject {
    ==
    getSubjectStatus
}

interface Observer {
    ==
    abstract update
}

class ConcreteObserver {
    ==
    update
}


@enduml